/media/aghose/DATA/anaconda39/bin/python cmd_runner.py scratch/configs/sst2_random_ngrams.json
/media/aghose/DATA/anaconda39/bin/python cmd_runner.py scratch/configs/sst2_random_wordvecs.json
/media/aghose/DATA/anaconda39/bin/python cmd_runner.py scratch/configs/sst2_random_MPNet.json
/media/aghose/DATA/anaconda39/bin/python cmd_runner.py scratch/configs/sst2_random_USE.json
/media/aghose/DATA/anaconda39/bin/python cmd_runner.py scratch/configs/sst2_cal_ngrams.json
/media/aghose/DATA/anaconda39/bin/python cmd_runner.py scratch/configs/sst2_cal_wordvecs.json
/media/aghose/DATA/anaconda39/bin/python cmd_runner.py scratch/configs/sst2_cal_MPNet.json
/media/aghose/DATA/anaconda39/bin/python cmd_runner.py scratch/configs/sst2_cal_USE.json
/media/aghose/DATA/anaconda39/bin/python cmd_runner.py scratch/configs/sst2_margin_ngrams.json
/media/aghose/DATA/anaconda39/bin/python cmd_runner.py scratch/configs/sst2_margin_wordvecs.json
/media/aghose/DATA/anaconda39/bin/python cmd_runner.py scratch/configs/sst2_margin_MPNet.json
/media/aghose/DATA/anaconda39/bin/python cmd_runner.py scratch/configs/sst2_margin_USE.json
/media/aghose/DATA/anaconda39/bin/python cmd_runner.py scratch/configs/sst2_dal_ngrams.json
/media/aghose/DATA/anaconda39/bin/python cmd_runner.py scratch/configs/sst2_dal_wordvecs.json
/media/aghose/DATA/anaconda39/bin/python cmd_runner.py scratch/configs/sst2_dal_MPNet.json
/media/aghose/DATA/anaconda39/bin/python cmd_runner.py scratch/configs/sst2_dal_USE.json
/media/aghose/DATA/anaconda39/bin/python cmd_runner.py scratch/configs/sst2_real_ngrams.json
/media/aghose/DATA/anaconda39/bin/python cmd_runner.py scratch/configs/sst2_real_wordvecs.json
/media/aghose/DATA/anaconda39/bin/python cmd_runner.py scratch/configs/sst2_real_MPNet.json
/media/aghose/DATA/anaconda39/bin/python cmd_runner.py scratch/configs/sst2_real_USE.json
/media/aghose/DATA/anaconda39/bin/python cmd_runner.py scratch/configs/dbpedia5_random_ngrams.json
/media/aghose/DATA/anaconda39/bin/python cmd_runner.py scratch/configs/dbpedia5_random_wordvecs.json
/media/aghose/DATA/anaconda39/bin/python cmd_runner.py scratch/configs/dbpedia5_random_MPNet.json
/media/aghose/DATA/anaconda39/bin/python cmd_runner.py scratch/configs/dbpedia5_random_USE.json
/media/aghose/DATA/anaconda39/bin/python cmd_runner.py scratch/configs/dbpedia5_cal_ngrams.json
/media/aghose/DATA/anaconda39/bin/python cmd_runner.py scratch/configs/dbpedia5_cal_wordvecs.json
/media/aghose/DATA/anaconda39/bin/python cmd_runner.py scratch/configs/dbpedia5_cal_MPNet.json
/media/aghose/DATA/anaconda39/bin/python cmd_runner.py scratch/configs/dbpedia5_cal_USE.json
/media/aghose/DATA/anaconda39/bin/python cmd_runner.py scratch/configs/dbpedia5_margin_ngrams.json
/media/aghose/DATA/anaconda39/bin/python cmd_runner.py scratch/configs/dbpedia5_margin_wordvecs.json
/media/aghose/DATA/anaconda39/bin/python cmd_runner.py scratch/configs/dbpedia5_margin_MPNet.json
/media/aghose/DATA/anaconda39/bin/python cmd_runner.py scratch/configs/dbpedia5_margin_USE.json
/media/aghose/DATA/anaconda39/bin/python cmd_runner.py scratch/configs/dbpedia5_dal_ngrams.json
/media/aghose/DATA/anaconda39/bin/python cmd_runner.py scratch/configs/dbpedia5_dal_wordvecs.json
/media/aghose/DATA/anaconda39/bin/python cmd_runner.py scratch/configs/dbpedia5_dal_MPNet.json
/media/aghose/DATA/anaconda39/bin/python cmd_runner.py scratch/configs/dbpedia5_dal_USE.json
/media/aghose/DATA/anaconda39/bin/python cmd_runner.py scratch/configs/dbpedia5_real_ngrams.json
/media/aghose/DATA/anaconda39/bin/python cmd_runner.py scratch/configs/dbpedia5_real_wordvecs.json
/media/aghose/DATA/anaconda39/bin/python cmd_runner.py scratch/configs/dbpedia5_real_MPNet.json
/media/aghose/DATA/anaconda39/bin/python cmd_runner.py scratch/configs/dbpedia5_real_USE.json
/media/aghose/DATA/anaconda39/bin/python cmd_runner.py scratch/configs/agnews_random_ngrams.json
/media/aghose/DATA/anaconda39/bin/python cmd_runner.py scratch/configs/agnews_random_wordvecs.json
/media/aghose/DATA/anaconda39/bin/python cmd_runner.py scratch/configs/agnews_random_MPNet.json
/media/aghose/DATA/anaconda39/bin/python cmd_runner.py scratch/configs/agnews_random_USE.json
/media/aghose/DATA/anaconda39/bin/python cmd_runner.py scratch/configs/agnews_cal_ngrams.json
/media/aghose/DATA/anaconda39/bin/python cmd_runner.py scratch/configs/agnews_cal_wordvecs.json
/media/aghose/DATA/anaconda39/bin/python cmd_runner.py scratch/configs/agnews_cal_MPNet.json
/media/aghose/DATA/anaconda39/bin/python cmd_runner.py scratch/configs/agnews_cal_USE.json
/media/aghose/DATA/anaconda39/bin/python cmd_runner.py scratch/configs/agnews_margin_ngrams.json
/media/aghose/DATA/anaconda39/bin/python cmd_runner.py scratch/configs/agnews_margin_wordvecs.json
/media/aghose/DATA/anaconda39/bin/python cmd_runner.py scratch/configs/agnews_margin_MPNet.json
/media/aghose/DATA/anaconda39/bin/python cmd_runner.py scratch/configs/agnews_margin_USE.json
/media/aghose/DATA/anaconda39/bin/python cmd_runner.py scratch/configs/agnews_dal_ngrams.json
/media/aghose/DATA/anaconda39/bin/python cmd_runner.py scratch/configs/agnews_dal_wordvecs.json
/media/aghose/DATA/anaconda39/bin/python cmd_runner.py scratch/configs/agnews_dal_MPNet.json
/media/aghose/DATA/anaconda39/bin/python cmd_runner.py scratch/configs/agnews_dal_USE.json
/media/aghose/DATA/anaconda39/bin/python cmd_runner.py scratch/configs/agnews_real_ngrams.json
/media/aghose/DATA/anaconda39/bin/python cmd_runner.py scratch/configs/agnews_real_wordvecs.json
/media/aghose/DATA/anaconda39/bin/python cmd_runner.py scratch/configs/agnews_real_MPNet.json
/media/aghose/DATA/anaconda39/bin/python cmd_runner.py scratch/configs/agnews_real_USE.json
/media/aghose/DATA/anaconda39/bin/python cmd_runner.py scratch/configs/imdb_random_ngrams.json
/media/aghose/DATA/anaconda39/bin/python cmd_runner.py scratch/configs/imdb_random_wordvecs.json
/media/aghose/DATA/anaconda39/bin/python cmd_runner.py scratch/configs/imdb_random_MPNet.json
/media/aghose/DATA/anaconda39/bin/python cmd_runner.py scratch/configs/imdb_random_USE.json
/media/aghose/DATA/anaconda39/bin/python cmd_runner.py scratch/configs/imdb_cal_ngrams.json
/media/aghose/DATA/anaconda39/bin/python cmd_runner.py scratch/configs/imdb_cal_wordvecs.json
/media/aghose/DATA/anaconda39/bin/python cmd_runner.py scratch/configs/imdb_cal_MPNet.json
/media/aghose/DATA/anaconda39/bin/python cmd_runner.py scratch/configs/imdb_cal_USE.json
/media/aghose/DATA/anaconda39/bin/python cmd_runner.py scratch/configs/imdb_margin_ngrams.json
/media/aghose/DATA/anaconda39/bin/python cmd_runner.py scratch/configs/imdb_margin_wordvecs.json
/media/aghose/DATA/anaconda39/bin/python cmd_runner.py scratch/configs/imdb_margin_MPNet.json
/media/aghose/DATA/anaconda39/bin/python cmd_runner.py scratch/configs/imdb_margin_USE.json
/media/aghose/DATA/anaconda39/bin/python cmd_runner.py scratch/configs/imdb_dal_ngrams.json
/media/aghose/DATA/anaconda39/bin/python cmd_runner.py scratch/configs/imdb_dal_wordvecs.json
/media/aghose/DATA/anaconda39/bin/python cmd_runner.py scratch/configs/imdb_dal_MPNet.json
/media/aghose/DATA/anaconda39/bin/python cmd_runner.py scratch/configs/imdb_dal_USE.json
/media/aghose/DATA/anaconda39/bin/python cmd_runner.py scratch/configs/imdb_real_ngrams.json
/media/aghose/DATA/anaconda39/bin/python cmd_runner.py scratch/configs/imdb_real_wordvecs.json
/media/aghose/DATA/anaconda39/bin/python cmd_runner.py scratch/configs/imdb_real_MPNet.json
/media/aghose/DATA/anaconda39/bin/python cmd_runner.py scratch/configs/imdb_real_USE.json
/media/aghose/DATA/anaconda39/bin/python cmd_runner.py scratch/configs/pubmed_random_ngrams.json
/media/aghose/DATA/anaconda39/bin/python cmd_runner.py scratch/configs/pubmed_random_wordvecs.json
/media/aghose/DATA/anaconda39/bin/python cmd_runner.py scratch/configs/pubmed_random_MPNet.json
/media/aghose/DATA/anaconda39/bin/python cmd_runner.py scratch/configs/pubmed_random_USE.json
/media/aghose/DATA/anaconda39/bin/python cmd_runner.py scratch/configs/pubmed_cal_ngrams.json
/media/aghose/DATA/anaconda39/bin/python cmd_runner.py scratch/configs/pubmed_cal_wordvecs.json
/media/aghose/DATA/anaconda39/bin/python cmd_runner.py scratch/configs/pubmed_cal_MPNet.json
/media/aghose/DATA/anaconda39/bin/python cmd_runner.py scratch/configs/pubmed_cal_USE.json
/media/aghose/DATA/anaconda39/bin/python cmd_runner.py scratch/configs/pubmed_margin_ngrams.json
/media/aghose/DATA/anaconda39/bin/python cmd_runner.py scratch/configs/pubmed_margin_wordvecs.json
/media/aghose/DATA/anaconda39/bin/python cmd_runner.py scratch/configs/pubmed_margin_MPNet.json
/media/aghose/DATA/anaconda39/bin/python cmd_runner.py scratch/configs/pubmed_margin_USE.json
/media/aghose/DATA/anaconda39/bin/python cmd_runner.py scratch/configs/pubmed_dal_ngrams.json
/media/aghose/DATA/anaconda39/bin/python cmd_runner.py scratch/configs/pubmed_dal_wordvecs.json
/media/aghose/DATA/anaconda39/bin/python cmd_runner.py scratch/configs/pubmed_dal_MPNet.json
/media/aghose/DATA/anaconda39/bin/python cmd_runner.py scratch/configs/pubmed_dal_USE.json
/media/aghose/DATA/anaconda39/bin/python cmd_runner.py scratch/configs/pubmed_real_ngrams.json
/media/aghose/DATA/anaconda39/bin/python cmd_runner.py scratch/configs/pubmed_real_wordvecs.json
/media/aghose/DATA/anaconda39/bin/python cmd_runner.py scratch/configs/pubmed_real_MPNet.json
/media/aghose/DATA/anaconda39/bin/python cmd_runner.py scratch/configs/pubmed_real_USE.json
